version: '3.3'

services:
  delivery-manager:
    image: wasteant/wasteant:delivery-manager-ubuntu.22.04
    container_name: delivery-manager-core
    build:
      context: .
      args:
        user: ${user}
        userid: ${userid}
        group: ${group}
        groupid: ${groupid}
    networks:
      - internal
    ports:
      - ${INET_HTTP_SERVER_PORT}:${INET_HTTP_SERVER_PORT}
      - ${DJANGO_SERVER_PORT}:${DJANGO_SERVER_PORT}
      - ${DATA_API_PORT}:${DATA_API_PORT}
      - ${EVENT_API_PORT}:${EVENT_API_PORT}
      - ${FLOWER_PORT}:${FLOWER_PORT}
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/home/$user/src
      - /media/wasteantadmin/production-data/analytics/alarms/delivery:/media/alarms/delivery
    user: ${user}

  # RabbitMQ Service
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: delivery-manager-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - .docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - internal
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

networks:
  internal:
    name: internal
    driver: bridge 
