# Generated by Django 4.2 on 2024-09-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=250)),
                ('event_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Events',
                'db_table': 'delivery_event',
            },
        ),
        migrations.CreateModel(
            name='DeliveryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=255)),
                ('delivery_start', models.DateTimeField()),
                ('delivery_end', models.DateTimeField(null=True)),
                ('delivery_status', models.CharField(default='pending', max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery State',
                'db_table': 'delivery_state',
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entity Types',
                'db_table': 'entity_type',
            },
        ),
        migrations.CreateModel(
            name='PlantEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uid', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Entities',
                'db_table': 'plant_entity',
            },
        ),
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=255)),
                ('plant_name', models.CharField(max_length=255)),
                ('plant_location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Info',
                'db_table': 'plant_info',
            },
        ),
        migrations.AddIndex(
            model_name='plantinfo',
            index=models.Index(fields=['plant_name', 'plant_location'], name='plant_info_plant_n_344778_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantinfo',
            unique_together={('plant_name', 'plant_location')},
        ),
        migrations.AddField(
            model_name='plantentity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.entitytype'),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.plantinfo'),
        ),
        migrations.AddField(
            model_name='deliverystate',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.plantentity'),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='event_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.plantentity'),
        ),
        migrations.AddIndex(
            model_name='deliveryevent',
            index=models.Index(fields=['event_location', 'event_timestamp'], name='delivery_ev_event_l_c88a03_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryevent',
            index=models.Index(fields=['status', 'event_timestamp', 'event_location'], name='delivery_ev_status_c0d925_idx'),
        ),
    ]
