# Generated by Django 4.2 on 2024-09-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Metadata',
                'db_table': 'metadata',
            },
        ),
        migrations.CreateModel(
            name='MetadataColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='database.metadata')),
            ],
            options={
                'verbose_name_plural': 'Metadata Columns',
                'db_table': 'metadata_column',
            },
        ),
        migrations.CreateModel(
            name='MetadataLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metadata_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='database.metadatacolumn')),
            ],
            options={
                'verbose_name_plural': 'Metadata Localizations',
                'db_table': 'metadata_localization',
            },
        ),
        migrations.CreateModel(
            name='MetadataFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='database.metadata')),
            ],
            options={
                'verbose_name_plural': 'Metadata Flags',
                'db_table': 'metadata_flags',
            },
        ),
        migrations.AddIndex(
            model_name='metadatalocalization',
            index=models.Index(fields=['metadata_column', 'language'], name='metadata_lo_metadat_651cbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metadatalocalization',
            unique_together={('metadata_column', 'language')},
        ),
        migrations.AddIndex(
            model_name='metadataflags',
            index=models.Index(fields=['metadata', 'column_name'], name='metadata_fl_metadat_8b47c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metadataflags',
            unique_together={('metadata', 'column_name')},
        ),
        migrations.AddIndex(
            model_name='metadatacolumn',
            index=models.Index(fields=['metadata', 'column_name'], name='metadata_co_metadat_4b7592_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metadatacolumn',
            unique_together={('metadata', 'column_name')},
        ),
    ]
