# Generated by Django 4.2 on 2024-09-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_metadata_metadatacolumn_metadatalocalization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatacolumn',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='metadataflags',
            name='description',
            field=models.TextField(default='N/A'),
        ),
    ]
