# Generated by Django 4.2 on 2024-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_metadatacolumn_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystate',
            name='delivery_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
