# Generated by Django 4.2 on 2024-10-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_deliverystate_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantinfo',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
