# Generated by Django 4.2 on 2025-02-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_plantinfo_domain_alter_plantinfo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=255, unique=True)),
                ('stream_topic', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('plant_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='database.plantentity')),
            ],
            options={
                'verbose_name_plural': 'Cameras',
                'db_table': 'camera',
            },
        ),
    ]
